[WIP] Move git logic to Git Manager
containers/fetchit pull request #177
Opened 2022-05-24 17:43 UTC by josephsawaya

Signed-off-by: Joseph <jsawaya@redhat.com>

2022-05-25 16:53 UTC, sallyom requested changes
see the note about the placement of hc.update, other than that this lgtm

2022-05-25 16:53 UTC, sallyom commented on pkg/engine/fetchit.go
>  	hc.update(mo.Target)
this update should be after you set the workingCommit, below, after this line: https://github.com/containers/fetchit/pull/177/files#diff-f909bb48f0bef398a8f323f6ebb382f1c1b48763963d34b5e90dfe6289b87b97R754

2022-05-26 16:06 UTC, sallyom commented
I'm cool to merge this, wdyt? 
/lgtm

2022-05-27 18:33 UTC, josephsawaya commented
Going to close this for now and come back to it later actually

2022-05-27 18:33 UTC, closed without merging